# Generated by Django 3.2.8 on 2021-11-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=80)),
                ('head0', models.CharField(default='', max_length=100)),
                ('head0_content', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=100)),
                ('head1_content', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=100)),
                ('head2_content', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
