# Generated by Django 3.2.8 on 2021-11-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blogpost_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='about',
            field=models.CharField(default='Summary about the blog', max_length=215),
        ),
    ]
