# Generated by Django 3.2.8 on 2021-11-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=-1)),
                ('update_desc', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
